name: Build under Ubuntu (with Google Cloud SDK)

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
          cache: gradle

        # This operation is specific to `gcloud-java` repository only.
      - name: Decrypt the credentials for the Spine-Dev service account
        run: ./config/scripts/decrypt.sh "$SPINE_DEV_CI_KEY" ./.github/keys/spine-dev-framework-ci.json.gpg ./spine-dev.json
        env:
          SPINE_DEV_CI_KEY: ${{ secrets.SPINE_DEV_CI_KEY }}

      - name: Build project and run tests
        run: ./gradlew build --stacktrace

      - name: Upload code coverage report
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          verbose: true
