name: Build under Windows

on: pull_request

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: zulu
          cache: gradle

      - name: Pull config
        run: git submodule update --init --recursive

        # The OS-managed Google Cloud SDK does not provide a Datastore emulator.
      - name: Remove the OS-managed Google Cloud SDK
        run: sudo apt-get remove google-cloud-sdk

      - name: Install Google Cloud SDK utility
        run: chmod +x ./scripts/install-gcloud.sh && ./scripts/install-gcloud.sh

        # Appends the `gcloud` utility to the PATH for this particular terminal session.
      - name: Install the Datastore emulator and Cloud Beta tools
        run: >
          source ~/google-cloud-sdk/path.bash.inc
          && gcloud components install cloud-datastore-emulator --quiet
          && gcloud components install beta --quiet

        # Appends the `gcloud` utility to the PATH for this particular terminal session.
      - name: Start the Datastore emulator
        run: >
          source ~/google-cloud-sdk/path.bash.inc
          && ./scripts/start-datastore.sh &

      - name: Build project and run tests
        shell: cmd
        run: gradlew.bat build --stacktrace
